version: '3.8'
services: 
  jenkins: 
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "60000:50000"
    volumes:
      - jenkins-tester:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-tester: 